version: '3.8'

services:
  backend:
    build: backend
    volumes:
      - .:/backend
    tty: true
    command: ["python", "-m", "uvicorn", "backend.app.api:app", "--host", "0.0.0.0", "--reload"]
    # command: ["/bin/bash"]
    ports:
      - '8000:8000'